echo "Installing asdf plugins"
asdf plugin add lazygit
asdf install lazygit latest
asdf global lazygit latest
asdf plugin add ripgrep
asdf install ripgrep latest
asdf global ripgrep latest
asdf global lazygit latest
asdf plugin add fzf https://github.com/kompiro/asdf-fzf.git
asdf install fzf latest
asdf global fzf latest
asdf plugin add bat
asdf install bat latest
asdf global bat latest
asdf plugin add fd
asdf install fd latest
asdf global fd latest
asdf plugin add eza
asdf install eza latest
asdf global eza latest
asdf plugin add delta
asdf install delta latest
asdf global delta latest
asdf plugin add bat-extras
asdf install bat-extras latest
asdf global bat-extras latest
